-- Seed: INTIMACY / 极限 (Extreme) / Dare
-- Safe to re-run: uses ON CONFLICT(id) DO UPDATE

insert into public.prompts (id, category_id, type, text, text_en, is_published, is_trial, topic) values
('in-ex-001','intimacy','dare','捆绑双手，跪地服从1分钟命令。','Bind hands, kneel, and obey a 1-minute command.',true,false,'极限'),
('in-ex-002','intimacy','dare','轻打臀部10下，并大声说出最私密的性癖。','Lightly spank buttocks 10 times, confessing a private kink aloud after each.',true,false,'极限'),
('in-ex-003','intimacy','dare','滴热蜡在敏感部位，边滴边描述疼痛带来的兴奋感。','Drip hot wax on sensitive areas, describing the thrill of pain while doing so.',true,false,'极限'),
('in-ex-004','intimacy','dare','用衣夹夹住乳头或耳垂，持续30秒，同时讲述一个SM幻想。','Clip clothespins on nipples or earlobes for 30 seconds, narrating an SM fantasy.',true,false,'极限'),
('in-ex-005','intimacy','dare','作为“性隶”爬行到对方脚边，亲吻鞋子并求饶。','Crawl as a "slave" to partner’s feet, kiss their shoes, and beg for mercy.',true,false,'极限'),
('in-ex-006','intimacy','dare','重复说出“我是个听话的性奴”，边说边自摸暴露部位。','Repeat "I''m an obedient sex slave" while touching exposed areas.',true,false,'极限'),
('in-ex-007','intimacy','dare','用电击玩具在私处附近轻度震动，描述电流带来的羞耻高潮。','Use an electro-shock toy lightly near private areas, describing the shameful orgasm from the current.',true,false,'极限'),
('in-ex-008','intimacy','dare','用冰块或牙签轻刺皮肤，同时分享疼痛的感觉。','Prick skin lightly with ice or a toothpick, sharing pain sensations.',true,false,'极限'),
('in-ex-009','intimacy','dare','强制窒息1分钟，期间讲述窒息幻想。','Restrict breathing for 1 minute, narrating a breath-play fantasy.',true,false,'极限'),
('in-ex-010','intimacy','dare','跪地模拟“黄金雨”场景（可用水代替），大声承认享受羞辱。','Kneel and simulate a "golden shower" (using water), loudly admitting enjoyment of humiliation.',true,false,'极限'),
('in-ex-011','intimacy','dare','鞭打后，站立展示痕迹，让对方点评“多么听话的性奴”。','After whipping, stand and show marks, letting partner comment on "such an obedient sex slave."',true,false,'极限'),
('in-ex-012','intimacy','dare','用绳子轻绑双手举过头顶，悬挂式站立2分钟，边晃边乞求释放。','Lightly bind hands above head with rope, stand suspended for 2 minutes, begging for release while swaying.',true,false,'极限'),
('in-ex-013','intimacy','dare','用巧克力或蜂蜜涂抹私处，然后要求对方舔干净。','Smear chocolate or honey on private areas, then have partner lick it off.',true,false,'极限'),
('in-ex-014','intimacy','dare','用手指掐捏皮肤，每掐一下计数并说出“谢谢主人惩罚我”。','Pinch skin with fingers, counting each pinch and saying, "Thank you, Master, for punishing me."',true,false,'极限'),
('in-ex-015','intimacy','dare','用可洗马克笔在私处写羞辱词，如“主人的玩具”，拍照留念后立即删除。','Write a humiliating phrase like "Master''s toy" on private areas with washable marker, take a photo, and delete it immediately.',true,false,'极限'),
('in-ex-016','intimacy','dare','戴项圈被链条牵着走一圈，边走边模仿小狗的叫声。','Wear a collar, be led by a chain for one lap, barking like a dog.',true,false,'极限'),
('in-ex-017','intimacy','dare','交替用冰块和热蜡刺激同一部位，描述冷热交替的羞耻快感。','Alternate ice and hot wax on the same area, describing the shameful thrill of temperature shifts.',true,false,'极限'),
('in-ex-018','intimacy','dare','保持姿势不动2分钟，任由对方撩拨敏感区而不许反应。','Hold a pose for 2 minutes, letting partner tease sensitive areas without reacting.',true,false,'极限'),
('in-ex-019','intimacy','dare','全裸站在落地窗前15秒，双手举过头顶，让想象中的“路人”欣赏。','Stand naked by a window for 15 seconds, hands above head, imagining "passersby" watching.',true,false,'极限'),
('in-ex-020','intimacy','dare','只穿风衣真空出门散步一小段，返回后详细描述羞耻感。','Wear only a trench coat with nothing underneath for a short walk, describing the shameful feeling afterward.',true,false,'极限'),
('in-ex-021','intimacy','dare','脱光衣服站立，让对方轮流点评每个身体部位的最羞耻之处。','Strip naked and stand, letting partner critique the most embarrassing body parts.',true,false,'极限'),
('in-ex-022','intimacy','dare','全裸面对镜子，边看边向对方描述展示自己最喜欢的身体部位。','Face a mirror naked, describing your favorite body part to your partner.',true,false,'极限'),
('in-ex-023','intimacy','dare','在一间暗室中全裸自摸1分钟，边做边讲述过程给伴侣。','Masturbate naked in a dark room for 1 minute, narrating the process to your partner.',true,false,'极限'),
('in-ex-024','intimacy','dare','用贴纸在身体上贴“淫荡”“奴隶”等词，穿衣服出门买东西（贴纸隐藏）。','Place stickers with words like "slut" or "slave" on your body, wear clothes over them, and go shopping.',true,false,'极限'),
('in-ex-025','intimacy','dare','模拟在伴侣面前如厕，边做边分享尴尬幻想。','Simulate using the toilet in front of your partner, sharing an embarrassing fantasy.',true,false,'极限'),
('in-ex-026','intimacy','dare','双手绑在身后，全裸跪地，任由伴侣用手机灯光“检查”私处细节。','Bind hands behind back, kneel naked, and let partner "inspect" private areas with a phone flashlight.',true,false,'极限'),
('in-ex-027','intimacy','dare','全裸自拍私密部位，发给伴侣后立即删除，并描述发送时的想法和感受。','Take a nude selfie of private areas, send to partner, delete immediately, and describe thoughts and feelings.',true,false,'极限'),
('in-ex-028','intimacy','dare','剧烈运动后全裸展示汗湿身体，被命令闻自己的体味并承认享受。','After intense exercise, show sweaty naked body, smell your own odor, and admit enjoying it.',true,false,'极限'),
('in-ex-029','intimacy','dare','跪地乞求对方“允许我脱衣服”，脱后保持跪姿2分钟。','Kneel and beg partner to "let me strip," then kneel for 2 minutes after undressing.',true,false,'极限'),
('in-ex-030','intimacy','dare','在阳台上全裸摆姿势15秒，想象楼下路人观看。','Pose naked on a balcony for 15 seconds, imagining passersby below.',true,false,'极限'),
('in-ex-031','intimacy','dare','如果有体毛，展示并让对方拔一根作为惩罚。','If you have body hair, show it and let partner pluck one strand as punishment.',true,false,'极限'),
('in-ex-032','intimacy','dare','用润滑油涂满私处，并在家具上摩擦。','Coat private areas with lube and rub against furniture.',true,false,'极限'),
('in-ex-033','intimacy','dare','全裸录音自己的呻吟声，回放给对方听并求反馈。','Record your naked moans, play them back to partner, and beg for feedback.',true,false,'极限'),
('in-ex-034','intimacy','dare','面对镜子全裸，服从镜中“自己”的命令自摸。','Face a mirror naked and obey your reflection’s command to masturbate.',true,false,'极限'),
('in-ex-035','intimacy','dare','全裸躺下，让对方仔细“检验”并点评。','Lie naked, letting partner closely "inspect" and critique your body.',true,false,'极限'),
('in-ex-036','intimacy','dare','保持性交插入不动3轮，每轮1分钟，期间讲述一个禁忌幻想。','Maintain penetration without moving for 3 rounds, each 1 minute, narrating a taboo fantasy.',true,false,'极限'),
('in-ex-037','intimacy','dare','跪地口交伴侣30秒，边做边眼神接触增加羞耻。','Kneel and perform oral sex on partner for 30 seconds, maintaining eye contact for shame.',true,false,'极限'),
('in-ex-038','intimacy','dare','尝试让伴侣连续高潮3次，失败则全裸道歉。','Try to bring partner to orgasm 3 times in a row; if you fail, apologize naked.',true,false,'极限'),
('in-ex-039','intimacy','dare','用振动玩具插入，保持不动1分钟，并描述感觉。','Insert a vibrating toy and hold still for 1 minute, describing the sensation.',true,false,'极限'),
('in-ex-040','intimacy','dare','自摸到边缘但不许高潮，重复5次，边忍边乞求允许。','Edge without climaxing, repeating 5 times, begging for permission to finish.',true,false,'极限'),
('in-ex-041','intimacy','dare','轻度指探或玩具插入肛门，边做边分享首次经历的尴尬。','Lightly finger or use a toy anally, sharing the embarrassment of your first experience.',true,false,'极限'),
('in-ex-042','intimacy','dare','尝试3个羞耻体位（如狗式），每个保持30秒并点评。','Try 3 shameful positions (e.g., doggy style), holding each for 30 seconds and commenting.',true,false,'极限'),
('in-ex-043','intimacy','dare','高潮后，用手指沾取体液涂抹在自己脸上作为标记。','After orgasm, smear bodily fluids on your face with a finger as a mark.',true,false,'极限'),
('in-ex-044','intimacy','dare','性交时戴耳机放大自己的呻吟，回放后分析。','Wear headphones to amplify moans during sex, then analyze the playback.',true,false,'极限'),
('in-ex-045','intimacy','dare','男性玩家忍住射精，失败则跪地清理（模拟）。','Male players try to delay ejaculation; if you fail, kneel and simulate cleanup.',true,false,'极限'),
('in-ex-046','intimacy','dare','跪地“崇拜”对方的私处，亲吻并赞美细节。','Kneel and "worship" partner’s private areas, kissing and praising details.',true,false,'极限'),
('in-ex-047','intimacy','dare','被绑住自摸到边缘，重复边缘3次。','While bound, edge 3 times without climaxing.',true,false,'极限'),
('in-ex-048','intimacy','dare','如果适用，模拟挤压分享奶水幻想的羞耻。','If applicable, simulate squeezing and sharing a lactation fantasy’s shame.',true,false,'极限'),
('in-ex-049','intimacy','dare','插入后计数每一下，达到10下后大声宣布“我是你的玩具”。','Count each thrust during penetration, announcing "I''m your toy" after 10.',true,false,'极限'),
('in-ex-050','intimacy','dare','全裸侍奉伴侣，端茶倒水并服从任意命令3分钟。','Serve partner naked, fetching tea or water and obeying commands for 3 minutes.',true,false,'极限'),
('in-ex-051','intimacy','dare','戴耳朵尾巴，模仿宠物爬行并乞食（用手指喂）。','Wear animal ears and tail, crawl like a pet, and beg for food from partner’s fingers.',true,false,'极限'),
('in-ex-052','intimacy','dare','模拟“老师/学生”，学生被惩罚脱衣写检讨。','Simulate a "teacher/student" scenario, with the student stripped and writing a confession.',true,false,'极限'),
('in-ex-053','intimacy','dare','作为“医生”检查对方私处，边检边问羞耻问题。','As a "doctor," inspect partner’s private areas, asking shameful questions.',true,false,'极限'),
('in-ex-054','intimacy','dare','被当作“家具”，全裸跪地当桌子，对方放东西在上。','Act as "furniture," kneeling naked as a table for partner to place items on.',true,false,'极限'),
('in-ex-055','intimacy','dare','扮演英雄被俘，脱衣接受“审讯”如自述弱点。','Play a captured superhero, stripping and confessing weaknesses during a "torture" interrogation.',true,false,'极限'),
('in-ex-056','intimacy','dare','模拟古罗马奴隶，表演脱衣舞。','Imitate an ancient Roman slave, performing a striptease.',true,false,'极限'),
('in-ex-057','intimacy','dare','被当作“甜点”，涂满奶油让伴侣舔干净。','Act as a "dessert," covered in whipped cream for partner to lick off.',true,false,'极限'),
('in-ex-058','intimacy','dare','模拟非血缘禁忌关系，讲述幻想细节（纯虚构）。','Simulate a non-blood-related taboo relationship, narrating a fantasy (purely fictional).',true,false,'极限'),
('in-ex-059','intimacy','dare','扮演秘书，被老板命令跪地口头报告私密事。','Play a secretary, kneeling to orally report private matters to a "boss."',true,false,'极限'),
('in-ex-060','intimacy','dare','扮演人鱼，被命令在浴缸中暴露下体。','Pose as a mermaid, exposing your lower body in a bathtub.',true,false,'极限'),
('in-ex-061','intimacy','dare','戴眼罩全裸自摸，对方需悄声指导增加羞耻。','Wear a blindfold and masturbate naked, with partner whispering guidance to increase shame.',true,false,'极限'),
('in-ex-062','intimacy','dare','戴耳塞服从无声手势，如脱衣或姿势。','Wear earplugs and obey silent gestures, such as stripping or posing.',true,false,'极限'),
('in-ex-063','intimacy','dare','被喂未知食物（安全），边吃边猜并分享尴尬。','Be fed unknown (safe) food, guessing its identity while sharing embarrassment.',true,false,'极限'),
('in-ex-064','intimacy','dare','绑眼耳鼻，全裸等待触摸，描述未知感。','Blindfold eyes, ears, and nose, wait naked for a touch, and describe the unknown sensation.',true,false,'极限'),
('in-ex-065','intimacy','dare','被撩拨敏感区至笑哭，乞求停止。','Be teased on sensitive areas until crying with laughter, begging to stop.',true,false,'极限'),
('in-ex-066','intimacy','dare','交替冰热刺激私处，忍耐到极限。','Alternate ice and heat on private areas, enduring to the limit.',true,false,'极限'),
('in-ex-067','intimacy','dare','闻对方体味后模仿高潮反应。','Smell partner’s body odor and mimic an orgasmic reaction.',true,false,'极限'),
('in-ex-068','intimacy','dare','用骰子决定脱衣次数或插入深度。','Roll dice to determine clothing removal or penetration depth.',true,false,'极限'),
('in-ex-069','intimacy','dare','全裸写色情日记，读给对方听。','Write an erotic diary naked and read it aloud to partner.',true,false,'极限'),
('in-ex-070','intimacy','dare','低语录制私密幻想，回放放大。','Whisper a private fantasy into a recorder, playing it back amplified.',true,false,'极限'),
('in-ex-071','intimacy','dare','描述湿梦细节并重演片段。','Describe a wet dream in detail and reenact a segment.',true,false,'极限'),
('in-ex-072','intimacy','dare','用笔在私处画临时纹身，展示含义。','Draw a temporary tattoo on private areas with a pen and explain its meaning.',true,false,'极限'),
('in-ex-073','intimacy','dare','用塔罗牌决定性行为，执行后反思羞耻。','Use tarot cards to decide a sexual act, perform it, and reflect on the shame.',true,false,'极限')
on conflict (id) do update set text = excluded.text, text_en = excluded.text_en, type = excluded.type, topic = excluded.topic, is_published = excluded.is_published, is_trial = excluded.is_trial, category_id = excluded.category_id;


