-- Seed: INTIMACY / 极限 (Extreme) / Truth
-- Safe to re-run: uses ON CONFLICT(id) DO UPDATE

insert into public.prompts (id, category_id, type, text, text_en, is_published, is_trial, topic) values
('in-ex-tr-001','intimacy','truth','你有没有在公共场合尝试过露出游戏，如果有，描述最刺激的那次？','Have you ever tried exhibitionism in public? If so, describe your most thrilling experience.',true,false,'极限'),
('in-ex-tr-002','intimacy','truth','你最极端的性癖是什么？','What''s your most extreme fetish?',true,false,'极限'),
('in-ex-tr-003','intimacy','truth','你最想尝试的SM道具是什么？','What SM prop are you most eager to try?',true,false,'极限'),
('in-ex-tr-004','intimacy','truth','描述你最疯狂的角色扮演情节，包括所有细节。','Describe your wildest role-play scenario, including all details.',true,false,'极限'),
('in-ex-tr-005','intimacy','truth','你对恋足癖的兴趣程度如何？','How interested are you in foot fetishism?',true,false,'极限'),
('in-ex-tr-006','intimacy','truth','你有没有在做爱时用过蜡烛或冰块？','Have you ever used candles or ice during sex?',true,false,'极限'),
('in-ex-tr-007','intimacy','truth','你的极限BDSM场景会包括什么元素？','What elements would your ultimate BDSM scene include?',true,false,'极限'),
('in-ex-tr-008','intimacy','truth','你有没有在工作中偷偷自慰过？','Have you ever masturbated secretly at work?',true,false,'极限'),
('in-ex-tr-009','intimacy','truth','体液会让你感到性兴奋吗？','Do bodily fluids turn you on?',true,false,'极限'),
('in-ex-tr-010','intimacy','truth','你有没有尝试过尿道扩张？','Have you ever tried urethral sounding?',true,false,'极限'),
('in-ex-tr-011','intimacy','truth','描述你对后门的最深度探索。','Describe your deepest exploration of anal play.',true,false,'极限'),
('in-ex-tr-012','intimacy','truth','你有没有参与过公开羞辱的性活动？','Have you ever engaged in public humiliation during sex?',true,false,'极限'),
('in-ex-tr-013','intimacy','truth','你的宠物扮演幻想中，你更喜欢当主人还是宠物？','In pet play fantasies, do you prefer being the master or the pet?',true,false,'极限'),
('in-ex-tr-014','intimacy','truth','尝试电击玩具会让你感到很兴奋吗？','Does the idea of using electric shock toys excite you?',true,false,'极限'),
('in-ex-tr-015','intimacy','truth','你有没有在陌生人面前裸体过？','Have you ever been naked in front of strangers?',true,false,'极限'),
('in-ex-tr-016','intimacy','truth','你的最极端性幻想涉及什么情节？','What''s the plot of your most extreme sexual fantasy?',true,false,'极限'),
('in-ex-tr-017','intimacy','truth','你对针刺或自我伤害类的性爱游戏的看法和经历？','What are your thoughts or experiences with needle play or self-harm in sex?',true,false,'极限'),
('in-ex-tr-018','intimacy','truth','你有尝试过在性爱过程中把食物当作道具增加情趣吗？','Have you ever used food as a prop to enhance sex?',true,false,'极限'),
('in-ex-tr-019','intimacy','truth','描述你对窒息游戏的兴趣和想法。','Describe your interest in breath play and your thoughts on it.',true,false,'极限'),
('in-ex-tr-020','intimacy','truth','你最想尝试的露出地点是哪里，为什么？','Where''s the most daring place you''d want to try exhibitionism, and why?',true,false,'极限'),
('in-ex-tr-021','intimacy','truth','你的小众性癖中，最不寻常的是什么？','What''s the most unusual of your niche fetishes?',true,false,'极限'),
('in-ex-tr-022','intimacy','truth','你对鞭打或打屁股的兴趣是多少？','How interested are you in whipping or spanking?',true,false,'极限'),
('in-ex-tr-023','intimacy','truth','你有没有在性爱中使用过药物增强效果？','Have you ever used drugs to enhance sexual experiences?',true,false,'极限'),
('in-ex-tr-024','intimacy','truth','描述你对乳胶或皮革服装的痴迷。','Describe your obsession with latex or leather clothing.',true,false,'极限'),
('in-ex-tr-025','intimacy','truth','你有没有尝试过拳交？','Have you ever tried fisting?',true,false,'极限'),
('in-ex-tr-026','intimacy','truth','你的最刺激偷窥经历是什么？','What''s your most thrilling voyeuristic experience?',true,false,'极限'),
('in-ex-tr-027','intimacy','truth','你对年龄扮演游戏的幻想包括什么？','What does your age-play fantasy involve?',true,false,'极限'),
('in-ex-tr-028','intimacy','truth','你有没有在公共交通上玩过性游戏？','Have you ever played sexual games on public transport?',true,false,'极限'),
('in-ex-tr-029','intimacy','truth','描述你对疼痛与快感的结合的最爱方式。','Describe your favorite way to combine pain and pleasure.',true,false,'极限'),
('in-ex-tr-030','intimacy','truth','你最想探索的动物扮演细节是什么？','What details of animal role-play do you most want to explore?',true,false,'极限'),
('in-ex-tr-031','intimacy','truth','你有没有用镜子或录像增强过性体验？','Have you ever used mirrors or recordings to enhance a sexual experience?',true,false,'极限'),
('in-ex-tr-032','intimacy','truth','极限束缚的性爱场景会让你兴奋吗？','Does the idea of extreme bondage excite you?',true,false,'极限'),
('in-ex-tr-033','intimacy','truth','你对体臭或汗味的性吸引如何？','How do body odors or sweat sexually attract you?',true,false,'极限'),
('in-ex-tr-034','intimacy','truth','你有没有参与过线上的性相关游戏？','Have you ever participated in online sex-related games?',true,false,'极限'),
('in-ex-tr-035','intimacy','truth','描述你对医疗扮演的最深度幻想。','Describe your deepest medical role-play fantasy.',true,false,'极限'),
('in-ex-tr-036','intimacy','truth','你最喜欢的感官剥夺方式是什么？','What''s your favorite form of sensory deprivation?',true,false,'极限'),
('in-ex-tr-037','intimacy','truth','你有没有在户外尝试过野战，地点是哪里？','Have you ever had outdoor sex? If so, where?',true,false,'极限'),
('in-ex-tr-038','intimacy','truth','你的最极端口交幻想涉及什么？','What''s your most extreme oral sex fantasy?',true,false,'极限'),
('in-ex-tr-039','intimacy','truth','你对纹身或刺青作为性标记的看法？','What''s your view on tattoos or piercings as sexual markers?',true,false,'极限'),
('in-ex-tr-040','intimacy','truth','你有没有用玩具模拟双重插入？','Have you ever used toys to simulate double penetration?',true,false,'极限'),
('in-ex-tr-041','intimacy','truth','描述你对催眠性游戏的兴趣。','Describe your interest in hypnotic sex games.',true,false,'极限'),
('in-ex-tr-042','intimacy','truth','你最想尝试的公开自慰地点是哪里？','Where''s the most daring place you''d want to try public masturbation?',true,false,'极限'),
('in-ex-tr-043','intimacy','truth','你有没有参与过跨性别角色扮演？','Have you ever engaged in transgender role-play?',true,false,'极限'),
('in-ex-tr-044','intimacy','truth','刺激的偷情会让你感到兴奋吗？','Does the thrill of an affair excite you?',true,false,'极限'),
('in-ex-tr-045','intimacy','truth','你对电击乳头或生殖器的想法？','What''s your take on electric stimulation of nipples or genitals?',true,false,'极限'),
('in-ex-tr-046','intimacy','truth','描述你对长期禁欲后释放的幻想。','Describe your fantasy of release after long-term abstinence.',true,false,'极限'),
('in-ex-tr-047','intimacy','truth','你最极端的小众癖好是如何在生活中实践的？','How do you practice your most extreme niche fetish in real life?',true,false,'极限')
on conflict (id) do update set text = excluded.text, text_en = excluded.text_en, type = excluded.type, topic = excluded.topic, is_published = excluded.is_published, is_trial = excluded.is_trial, category_id = excluded.category_id;


