import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthStatus from "@/components/AuthStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full max-w-5xl mx-auto flex items-center justify-between p-4">
          <Link href="/" className="font-medium">Thousandsmore</Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link href="/pricing" className="hover:underline">定价</Link>
            <Link href="/restore" className="hover:underline">恢复购买</Link>
            <AuthStatus />
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
