import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Script from "next/script";
import LangToggle from "@/components/LangToggle";

// font loaders must be in module scope
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 在首页首屏前隐藏导航，避免闪烁。使用 beforeInteractive 确保尽早执行 */}
        <Script id="hide-nav-on-home" strategy="beforeInteractive">
          {`try{if(typeof window!=='undefined'&&window.location&&window.location.pathname==='\/'){document.documentElement.classList.add('hide-nav');}}catch(e){}`}
        </Script>
        <header className="top-nav w-full max-w-5xl mx-auto flex items-center justify-between p-4">
          <Link href="/" className="font-medium">Thousandsmore</Link>
          <LangToggle />
        </header>
        {children}
      </body>
    </html>
  );
}
