import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { useLang, setLang } from "@/lib/lang";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const lang = (typeof window !== "undefined" ? require("@/lib/lang") : { useLang: () => "zh" as const }).useLang?.() ?? "zh";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 在首页首屏前隐藏导航，避免闪烁。使用 beforeInteractive 确保尽早执行 */}
        <Script id="hide-nav-on-home" strategy="beforeInteractive">
          {`try{if(typeof window!=='undefined'&&window.location&&window.location.pathname==='\/'){document.documentElement.classList.add('hide-nav');}}catch(e){}`}
        </Script>
        <header className="top-nav w-full max-w-5xl mx-auto flex items-center justify-between p-4">
          <Link href="/" className="font-medium">Thousandsmore</Link>
          <nav className="flex items-center gap-4 text-sm">
            <Link href="/pricing" className="hover:underline">{lang === "en" ? "Pricing" : "定价"}</Link>
            <Link href="/restore" className="hover:underline">{lang === "en" ? "Restore" : "恢复购买"}</Link>
            <button onClick={() => setLang(lang === "en" ? "zh" : "en")} className="px-3 py-1 rounded-full border hover:bg-black/5">
              {lang === "en" ? "中 / En" : "中 / En"}
            </button>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
